
# -- Sets how many replicas of the application to run
replicaCount: 1

image:
  # -- Sets the container image repository to pull from.
  repository: someRepo/someDotNetApp
  # -- Sets the pull policy for images. [More details](https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy)
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: latest

# -- This is for the secrets for pulling an image from a private repository. [More details](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)
# @default -- ~empty
imagePullSecrets: []

# -- Overrides the chart name
# @default -- ~empty
nameOverride: ""

# -- Overrides the chart full name
# @default -- ~empty
fullnameOverride: ""

# -- This section builds out the service account. [More details](https://kubernetes.io/docs/concepts/security/service-accounts/)
# @default -- Creates and automounts a service account with the same name as the release name.
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# -- Annotations to be added to all pods
# @default -- ~empty
podAnnotations: {}

# -- Labels to be added to all pods
# @default -- ~empty
podLabels: {}

# -- Sets the security context for all pods. [More details](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
# @default -- ~empty
podSecurityContext: {}

# -- Sets the security context for all containers. [More details](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
# @default -- ~empty
securityContext: {}

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
startupProbe:
  httpGet:
    path: /
    port: http

nodeSelector: {}

tolerations: []

affinity: {}

###
# Application Settings
###

appSettings:
  ConnectionStrings:
    # -- Sets the Postgres connection string
    # @default -- ~empty
    PostgresContext: 
  # -- Sets the port the application listens on
  httpsPort: 5443
  # -- This and example of how a map/list would look if you leave the automatic default generation
  someMap:
    someNestedValue: ""
    listInMap:
      - item1
      - item2
    mapInMap: {}

###
# Most of these settings are not intended to be relied on for production deployments but undeniably useful when troubleshooting, trying out a new tool/feature, workarounds, etc
###

extraVolumes: []
extraVolumeMounts: []

additionalEnvironmentVariables: []

# -- Adhoc Kubernetes resources to be applied during the helm install/upgrade. This is not only super useful for DevOps tooling that your chart doesn't need to be concerned about, but can also be used for added tooling in dev environments without running the risk of accidentally making it to prod
# @default -- Disabled with no resources
customResources:
  # -- Whether to render custom resources
  enabled: false
  # -- Map of name to Kubernetes manifest objects
  # @default -- ~empty
  resources: {}